#!/bin/sh

# Grab the repo path just in case
repo="$(grep 'repo_path' "$HOME/.bsm/app.cfg" | cut -d= -f2)"

# Remove ${s_appname} from the system
rm -rf "$HOME/.bsm"
rm "$HOME/bin/bsm"
[ -e "$HOME/.bash_completion.d/bsm-comp" ] && rm "$HOME/.bash_completion.d/bsm-comp"

# Ask if the user would like to remove the repo
printf "Would you like to remove the repo as well? [Y/n] "
read -r yn
yn="$(printf '%s' "$yn" | tr '[:upper:]' '[:lower:]')"
[ "$yn" = 'y' ] && rm -rf "$repo"

# Let the user know that all of ${s_appname}'s files have been removed
printf "All of bsm's files have been removed.\n"
printf "You may need to update your \`~/.bashrc\` file to remove any bsm remnants.\n"